name: Node.js CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: npm
    - run: npm ci
    - run: npm i ffmpeg-static
    - run: npm i @discordjs/opus
    - run: npm i @discordjs/voice
    - run: |
        touch .env
        echo token=${{ secrets.token }} > .env
    - run: node index.js
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
